<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds with 200+ comprehensive skills.
     */
    public function run(): void
    {
        $skills = [
            // Software Engineering & Programming Languages
            ['name' => 'Python', 'category' => 'Software Engineering'],
            ['name' => 'JavaScript', 'category' => 'Software Engineering'],
            ['name' => 'TypeScript', 'category' => 'Software Engineering'],
            ['name' => 'Java', 'category' => 'Software Engineering'],
            ['name' => 'C++', 'category' => 'Software Engineering'],
            ['name' => 'C#', 'category' => 'Software Engineering'],
            ['name' => 'Go (Golang)', 'category' => 'Software Engineering'],
            ['name' => 'Rust', 'category' => 'Software Engineering'],
            ['name' => 'PHP', 'category' => 'Software Engineering'],
            ['name' => 'Ruby', 'category' => 'Software Engineering'],
            ['name' => 'Kotlin', 'category' => 'Software Engineering'],
            ['name' => 'Swift', 'category' => 'Software Engineering'],
            ['name' => 'Scala', 'category' => 'Software Engineering'],
            ['name' => 'Elixir', 'category' => 'Software Engineering'],
            ['name' => 'SQL', 'category' => 'Software Engineering'],
            ['name' => 'R', 'category' => 'Software Engineering'],
            ['name' => 'Dart', 'category' => 'Software Engineering'],
            ['name' => 'Assembly', 'category' => 'Software Engineering'],
            ['name' => 'MATLAB', 'category' => 'Software Engineering'],
            ['name' => 'Bash / Shell Scripting', 'category' => 'Software Engineering'],
            ['name' => 'Perl', 'category' => 'Software Engineering'],
            ['name' => 'Haskell', 'category' => 'Software Engineering'],
            ['name' => 'Lua', 'category' => 'Software Engineering'],
            ['name' => 'Julia', 'category' => 'Software Engineering'],
            ['name' => 'Groovy', 'category' => 'Software Engineering'],
            ['name' => 'Objective-C', 'category' => 'Software Engineering'],
            ['name' => 'F#', 'category' => 'Software Engineering'],
            ['name' => 'Erlang', 'category' => 'Software Engineering'],
            ['name' => 'Clojure', 'category' => 'Software Engineering'],
            ['name' => 'Zig', 'category' => 'Software Engineering'],
            ['name' => 'COBOL', 'category' => 'Software Engineering'],
            ['name' => 'Fortran', 'category' => 'Software Engineering'],
            ['name' => 'VBA', 'category' => 'Software Engineering'],
            ['name' => 'Object-Oriented Programming (OOP)', 'category' => 'Software Engineering'],
            ['name' => 'Functional Programming', 'category' => 'Software Engineering'],
            ['name' => 'Data Structures & Algorithms', 'category' => 'Software Engineering'],
            ['name' => 'Design Patterns', 'category' => 'Software Engineering'],

            // Web Development & Frameworks
            ['name' => 'React.js', 'category' => 'Web Development'],
            ['name' => 'Next.js', 'category' => 'Web Development'],
            ['name' => 'Vue.js', 'category' => 'Web Development'],
            ['name' => 'Angular', 'category' => 'Web Development'],
            ['name' => 'Node.js', 'category' => 'Web Development'],
            ['name' => 'Express.js', 'category' => 'Web Development'],
            ['name' => 'Laravel', 'category' => 'Web Development'],
            ['name' => 'Django', 'category' => 'Web Development'],
            ['name' => 'Flask', 'category' => 'Web Development'],
            ['name' => 'Spring Boot', 'category' => 'Web Development'],
            ['name' => 'ASP.NET Core', 'category' => 'Web Development'],
            ['name' => 'Ruby on Rails', 'category' => 'Web Development'],
            ['name' => 'Tailwind CSS', 'category' => 'Web Development'],
            ['name' => 'Bootstrap', 'category' => 'Web Development'],
            ['name' => 'Svelte', 'category' => 'Web Development'],
            ['name' => 'SvelteKit', 'category' => 'Web Development'],
            ['name' => 'Fastify', 'category' => 'Web Development'],
            ['name' => 'HTML5', 'category' => 'Web Development'],
            ['name' => 'CSS3 / SASS', 'category' => 'Web Development'],
            ['name' => 'GraphQL', 'category' => 'Web Development'],
            ['name' => 'RESTful API Architecture', 'category' => 'Web Development'],
            ['name' => 'WebSockets', 'category' => 'Web Development'],
            ['name' => 'gRPC', 'category' => 'Web Development'],
            ['name' => 'NestJS', 'category' => 'Web Development'],
            ['name' => 'Nuxt.js', 'category' => 'Web Development'],
            ['name' => 'Remix', 'category' => 'Web Development'],
            ['name' => 'Gatsby', 'category' => 'Web Development'],
            ['name' => 'Alpine.js', 'category' => 'Web Development'],
            ['name' => 'WebAssembly (Wasm)', 'category' => 'Web Development'],
            ['name' => 'Microservices Architecture', 'category' => 'Web Development'],
            ['name' => 'Serverless Architecture', 'category' => 'Web Development'],
            ['name' => 'Inertia.js', 'category' => 'Web Development'],
            ['name' => 'jQuery', 'category' => 'Web Development'],
            ['name' => 'Web Performance Optimization', 'category' => 'Web Development'],
            ['name' => 'Progressive Web Apps (PWA)', 'category' => 'Web Development'],

            // Mobile App Development
            ['name' => 'React Native', 'category' => 'Mobile Development'],
            ['name' => 'Flutter', 'category' => 'Mobile Development'],
            ['name' => 'iOS Development', 'category' => 'Mobile Development'],
            ['name' => 'Android Development', 'category' => 'Mobile Development'],
            ['name' => 'SwiftUI', 'category' => 'Mobile Development'],
            ['name' => 'Jetpack Compose', 'category' => 'Mobile Development'],
            ['name' => 'Ionic Framework', 'category' => 'Mobile Development'],
            ['name' => 'Xamarin', 'category' => 'Mobile Development'],
            ['name' => 'Kotlin Multiplatform (KMP)', 'category' => 'Mobile Development'],
            ['name' => 'Cordova / PhoneGap', 'category' => 'Mobile Development'],
            ['name' => 'Mobile Security', 'category' => 'Mobile Development'],
            ['name' => 'App Store Optimization (ASO)', 'category' => 'Mobile Development'],
            ['name' => 'Fastlane', 'category' => 'Mobile Development'],

            // DevOps, Cloud & Infrastructure
            ['name' => 'Amazon Web Services (AWS)', 'category' => 'DevOps & Cloud'],
            ['name' => 'Microsoft Azure', 'category' => 'DevOps & Cloud'],
            ['name' => 'Google Cloud Platform (GCP)', 'category' => 'DevOps & Cloud'],
            ['name' => 'Docker', 'category' => 'DevOps & Cloud'],
            ['name' => 'Kubernetes', 'category' => 'DevOps & Cloud'],
            ['name' => 'Terraform', 'category' => 'DevOps & Cloud'],
            ['name' => 'Ansible', 'category' => 'DevOps & Cloud'],
            ['name' => 'Jenkins', 'category' => 'DevOps & Cloud'],
            ['name' => 'GitHub Actions', 'category' => 'DevOps & Cloud'],
            ['name' => 'GitLab CI/CD', 'category' => 'DevOps & Cloud'],
            ['name' => 'Nginx', 'category' => 'DevOps & Cloud'],
            ['name' => 'Apache HTTP Server', 'category' => 'DevOps & Cloud'],
            ['name' => 'Linux Administration', 'category' => 'DevOps & Cloud'],
            ['name' => 'Unix Administration', 'category' => 'DevOps & Cloud'],
            ['name' => 'Prometheus', 'category' => 'DevOps & Cloud'],
            ['name' => 'Grafana', 'category' => 'DevOps & Cloud'],
            ['name' => 'Helm', 'category' => 'DevOps & Cloud'],
            ['name' => 'OpenShift', 'category' => 'DevOps & Cloud'],
            ['name' => 'CircleCI', 'category' => 'DevOps & Cloud'],
            ['name' => 'Cloudflare', 'category' => 'DevOps & Cloud'],
            ['name' => 'Serverless Framework', 'category' => 'DevOps & Cloud'],
            ['name' => 'HashiCorp Vault', 'category' => 'DevOps & Cloud'],
            ['name' => 'Datadog', 'category' => 'DevOps & Cloud'],
            ['name' => 'Splunk', 'category' => 'DevOps & Cloud'],
            ['name' => 'Elastic Stack (ELK)', 'category' => 'DevOps & Cloud'],
            ['name' => 'Infrastructure as Code (IaC)', 'category' => 'DevOps & Cloud'],
            ['name' => 'Site Reliability Engineering (SRE)', 'category' => 'DevOps & Cloud'],

            // Data Science, AI & Machine Learning
            ['name' => 'Machine Learning', 'category' => 'Data & AI'],
            ['name' => 'Deep Learning', 'category' => 'Data & AI'],
            ['name' => 'PyTorch', 'category' => 'Data & AI'],
            ['name' => 'TensorFlow', 'category' => 'Data & AI'],
            ['name' => 'Pandas', 'category' => 'Data & AI'],
            ['name' => 'NumPy', 'category' => 'Data & AI'],
            ['name' => 'Scikit-Learn', 'category' => 'Data & AI'],
            ['name' => 'OpenAI API & LLMs', 'category' => 'Data & AI'],
            ['name' => 'Computer Vision', 'category' => 'Data & AI'],
            ['name' => 'Natural Language Processing (NLP)', 'category' => 'Data & AI'],
            ['name' => 'Data Engineering', 'category' => 'Data & AI'],
            ['name' => 'Apache Spark', 'category' => 'Data & AI'],
            ['name' => 'Snowflake', 'category' => 'Data & AI'],
            ['name' => 'Databricks', 'category' => 'Data & AI'],
            ['name' => 'Power BI', 'category' => 'Data & AI'],
            ['name' => 'Tableau', 'category' => 'Data & AI'],
            ['name' => 'Apache Kafka', 'category' => 'Data & AI'],
            ['name' => 'Hadoop', 'category' => 'Data & AI'],
            ['name' => 'Apache Airflow', 'category' => 'Data & AI'],
            ['name' => 'Data Mining', 'category' => 'Data & AI'],
            ['name' => 'Predictive Modeling', 'category' => 'Data & AI'],
            ['name' => 'Reinforcement Learning', 'category' => 'Data & AI'],
            ['name' => 'MLOps', 'category' => 'Data & AI'],
            ['name' => 'LLM Fine-Tuning & RAG', 'category' => 'Data & AI'],
            ['name' => 'LangChain', 'category' => 'Data & AI'],
            ['name' => 'Keras', 'category' => 'Data & AI'],
            ['name' => 'OpenCV', 'category' => 'Data & AI'],
            ['name' => 'Big Data Analytics', 'category' => 'Data & AI'],

            // Database & Storage Technologies
            ['name' => 'PostgreSQL', 'category' => 'Database'],
            ['name' => 'MySQL', 'category' => 'Database'],
            ['name' => 'MongoDB', 'category' => 'Database'],
            ['name' => 'Redis', 'category' => 'Database'],
            ['name' => 'Elasticsearch', 'category' => 'Database'],
            ['name' => 'Cassandra', 'category' => 'Database'],
            ['name' => 'Firebase Realtime Database', 'category' => 'Database'],
            ['name' => 'DynamoDB', 'category' => 'Database'],
            ['name' => 'Oracle Database', 'category' => 'Database'],
            ['name' => 'MariaDB', 'category' => 'Database'],
            ['name' => 'Neo4j (Graph Database)', 'category' => 'Database'],
            ['name' => 'CockroachDB', 'category' => 'Database'],
            ['name' => 'SQLite', 'category' => 'Database'],
            ['name' => 'Microsoft SQL Server', 'category' => 'Database'],
            ['name' => 'Supabase', 'category' => 'Database'],
            ['name' => 'Amazon RDS', 'category' => 'Database'],
            ['name' => 'Vector Databases (Pinecone / Milvus)', 'category' => 'Database'],
            ['name' => 'Database Administration (DBA)', 'category' => 'Database'],
            ['name' => 'Database Migration & Sharding', 'category' => 'Database'],

            // Graphic Design, UI/UX & Creative Tools
            ['name' => 'Figma', 'category' => 'Design & Creative'],
            ['name' => 'Adobe XD', 'category' => 'Design & Creative'],
            ['name' => 'Adobe Photoshop', 'category' => 'Design & Creative'],
            ['name' => 'Adobe Illustrator', 'category' => 'Design & Creative'],
            ['name' => 'Adobe After Effects', 'category' => 'Design & Creative'],
            ['name' => 'Adobe Premiere Pro', 'category' => 'Design & Creative'],
            ['name' => 'Adobe InDesign', 'category' => 'Design & Creative'],
            ['name' => 'UI Design', 'category' => 'Design & Creative'],
            ['name' => 'UX Research', 'category' => 'Design & Creative'],
            ['name' => 'Wireframing & Prototyping', 'category' => 'Design & Creative'],
            ['name' => 'Brand Identity Design', 'category' => 'Design & Creative'],
            ['name' => 'Motion Graphics', 'category' => 'Design & Creative'],
            ['name' => 'Blender (3D Graphics)', 'category' => 'Design & Creative'],
            ['name' => '3D Modeling & Rendering', 'category' => 'Design & Creative'],
            ['name' => 'Canva', 'category' => 'Design & Creative'],
            ['name' => 'Sketch', 'category' => 'Design & Creative'],
            ['name' => 'Graphic Design', 'category' => 'Design & Creative'],
            ['name' => 'User Journey Mapping', 'category' => 'Design & Creative'],
            ['name' => 'Design Systems & Component Libraries', 'category' => 'Design & Creative'],
            ['name' => 'Typography & Layout', 'category' => 'Design & Creative'],
            ['name' => 'Character Animation', 'category' => 'Design & Creative'],
            ['name' => 'CorelDRAW', 'category' => 'Design & Creative'],
            ['name' => 'DaVinci Resolve', 'category' => 'Design & Creative'],
            ['name' => 'Vector Illustration', 'category' => 'Design & Creative'],
            ['name' => 'Logo Design', 'category' => 'Design & Creative'],
            ['name' => 'Infographic Design', 'category' => 'Design & Creative'],

            // Cybersecurity, Networking & Systems
            ['name' => 'Penetration Testing', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Ethical Hacking', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Network Security', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Information Security (InfoSec)', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Wireshark', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'OWASP Security Standards', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Cloud Security', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'SIEM (Security Event Management)', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Firewall & VPN Administration', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Cryptography & Encryption', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Incident Response', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Vulnerability Assessment', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Cisco Networking (CCNA/CCNP)', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Identity & Access Management (IAM)', 'category' => 'Cybersecurity & Systems'],
            ['name' => 'Metasploit Framework', 'category' => 'Cybersecurity & Systems'],

            // Quality Assurance & Software Testing
            ['name' => 'Selenium', 'category' => 'QA & Testing'],
            ['name' => 'Cypress', 'category' => 'QA & Testing'],
            ['name' => 'Playwright', 'category' => 'QA & Testing'],
            ['name' => 'Jest', 'category' => 'QA & Testing'],
            ['name' => 'JUnit', 'category' => 'QA & Testing'],
            ['name' => 'Postman', 'category' => 'QA & Testing'],
            ['name' => 'Automated Software Testing', 'category' => 'QA & Testing'],
            ['name' => 'Manual Software Testing', 'category' => 'QA & Testing'],
            ['name' => 'Performance & Load Testing', 'category' => 'QA & Testing'],
            ['name' => 'LoadRunner', 'category' => 'QA & Testing'],
            ['name' => 'Cucumber (BDD)', 'category' => 'QA & Testing'],
            ['name' => 'PyTest', 'category' => 'QA & Testing'],
            ['name' => 'Mocha / Chai', 'category' => 'QA & Testing'],
            ['name' => 'Appium (Mobile Automation)', 'category' => 'QA & Testing'],
            ['name' => 'API Automated Testing', 'category' => 'QA & Testing'],
            ['name' => 'Bug Tracking & Regression Testing', 'category' => 'QA & Testing'],

            // Product, Project & Business Management
            ['name' => 'Agile Methodologies', 'category' => 'Management & Business'],
            ['name' => 'Scrum Framework', 'category' => 'Management & Business'],
            ['name' => 'Kanban Methodology', 'category' => 'Management & Business'],
            ['name' => 'JIRA Software', 'category' => 'Management & Business'],
            ['name' => 'Asana', 'category' => 'Management & Business'],
            ['name' => 'Product Management', 'category' => 'Management & Business'],
            ['name' => 'Technical Writing & Documentation', 'category' => 'Management & Business'],
            ['name' => 'Business Analysis', 'category' => 'Management & Business'],
            ['name' => 'Product Roadmap Planning', 'category' => 'Management & Business'],
            ['name' => 'Trello', 'category' => 'Management & Business'],
            ['name' => 'Confluence', 'category' => 'Management & Business'],
            ['name' => 'Risk Management', 'category' => 'Management & Business'],
            ['name' => 'Stakeholder Communication', 'category' => 'Management & Business'],
            ['name' => 'Requirements Gathering', 'category' => 'Management & Business'],
            ['name' => 'Project Scheduling & Budgeting', 'category' => 'Management & Business'],

            // Digital Marketing & Content Strategy
            ['name' => 'SEO (Search Engine Optimization)', 'category' => 'Digital Marketing'],
            ['name' => 'Content Strategy & Copywriting', 'category' => 'Digital Marketing'],
            ['name' => 'Digital Marketing', 'category' => 'Digital Marketing'],
            ['name' => 'Google Analytics 4 (GA4)', 'category' => 'Digital Marketing'],
            ['name' => 'Social Media Marketing (SMM)', 'category' => 'Digital Marketing'],
            ['name' => 'Email Marketing Automation', 'category' => 'Digital Marketing'],
            ['name' => 'PPC (Pay-Per-Click) Advertising', 'category' => 'Digital Marketing'],
            ['name' => 'SEM (Search Engine Marketing)', 'category' => 'Digital Marketing'],
            ['name' => 'Conversion Rate Optimization (CRO)', 'category' => 'Digital Marketing'],
            ['name' => 'HubSpot CRM / Marketing', 'category' => 'Digital Marketing'],
        ];

        foreach ($skills as $skill) {
            Skill::firstOrCreate(['name' => $skill['name']], $skill);
        }
    }
}
